uquvchilar = ["Odil", "Qahramon", "Sodiq", "Olim"]
uquvchilar.append("Hasan")
print(uquvchilar)
uquvchilar.insert(2, "Sirojiddin")
print(uquvchilar)
uquvchilar.append("Sodiq")
print(uquvchilar)
print(uquvchilar.count("Sodiq"))
uquvchilar.extend(uquvchilar)
print(uquvchilar)
print(uquvchilar.index("Olim"))
uquvchilar.clear()
print(uquvchilar)
print(len(uquvchilar))